# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSx9eJaMCQytqYNO6tcMC5q5uAQ6W7ZL
"""

import os

# Create the directory structure for a Flask app
os.makedirs('templates', exist_ok=True)
os.makedirs('static/css', exist_ok=True)

print('Project structure created successfully.')

from flask import Flask, render_template

app = Flask(__name__)

@app.route('/')
def landing():
    return render_template('landing.html')

@app.route('/login')
def auth():
    return render_template('auth.html')

@app.route('/dashboard')
def dashboard():
    return render_template('dashboard.html')

if __name__ == '__main__':
    # In Colab, we don't usually run the server this way, but this is the code structure
    print('Flask app defined.')

css_content = """
:root {
    --primary: #00975f;
    --primary-light: #34d399;
    --bg: #f8fafc;
    --surface: #ffffff;
    --text: #0f172a;
    --muted: #64748b;
    --border: #e2e8f0;
    --radius-btn: 12px;
    --radius-card: 16px;
}

body {
    font-family: 'Inter', sans-serif;
    background-color: var(--bg);
    color: var(--text);
    margin: 0;
}

.btn-primary {
    background-color: var(--primary);
    color: white;
    border-radius: var(--radius-btn);
    padding: 12px 24px;
    border: none;
    transition: transform 0.2s;
}

.btn-primary:hover {
    transform: translateY(-2px);
    background-color: var(--primary-light);
}

.card {
    background: var(--surface);
    padding: 24px;
    border-radius: var(--radius-card);
    box-shadow: 0 4px 20px rgba(0,0,0,0.05);
    border: 1px solid var(--border);
}

.navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 20px 5%;
    background: white;
    border-bottom: 1px solid var(--border);
}

.hero {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 40px;
    padding: 80px 5%;
    align-items: center;
}
"""

with open('static/css/style.css', 'w') as f:
    f.write(css_content)
print('CSS file generated.')

landing_html = """
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
    <title>VFStudent - Smart Job Finding</title>
</head>
<body>
    <nav class="navbar">
        <div class="logo"><strong>VFStudent</strong></div>
        <div class="menu">Jobs | Internship | About</div>
        <div class="auth-btns">
            <button class="btn-primary">Login</button>
        </div>
    </nav>

    <section class="hero">
        <div class="hero-left">
            <h1>Smart Job Finding Platform for Students</h1>
            <p style="color: var(--muted);">AI recommends suitable jobs for you</p>
            <button class="btn-primary">Find a job</button>
            <button class="btn-secondary" style="margin-left:10px;">Sign up</button>
        </div>
        <div class="hero-right">
            <div class="card">[Illustration: Student working]</div>
        </div>
    </section>
</body>
</html>
"""

with open('templates/landing.html', 'w') as f:
    f.write(landing_html)
print('Landing template generated.')